services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    # Serve through default port of nextjs application
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: no

  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URL=mongodb://db:27017/inventory
    restart: no
    command: yarn dev
