# Copyright (c) 2025 Eclipse Foundation.
# 
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: MIT

services:
  frontend:
    platform: linux/amd64
    container_name: inventory-frontend
    networks:
      - inventory-network
    # depends_on:
    #   - backend
    env_file:
      - .env.fe

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    platform: linux/amd64
    depends_on:
      - db
    container_name: inventory-backend
    ports:
      - '3001:3001'
    networks:
      - inventory-network

  db:
    volumes:
      - dbdata:/data/db
    image: mongo:4.4.29-focal
    container_name: inventory-db
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
