services:
  frontend:
    platform: linux/amd64
    container_name: inventory-frontend
    networks:
      - inventory-network
    depends_on:
      - backend
      
  backend:
    platform: linux/amd64
    container_name: inventory-backend
    ports:
      - "3001:3000"
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge