# Copyright (c) 2025 Eclipse Foundation.
# 
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: boschvn/inventory-fe:latest
    # Serve through nginx of docker container
    ports:
      - '3000:3000'
    restart: always

  backend:
    image: boschvn/inventory-be:latest
    env_file:
      - .env
    restart: always
    command: yarn start
