services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: boschvn/inventory-fe:latest
    # Serve through nginx of docker container
    ports:
      - '3000:80'
    restart: always

  backend:
    image: boschvn/inventory-be:latest
    env_file:
      - .env
    restart: always
    command: yarn start
