FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=development
RUN chown -R node:node /app
USER node
COPY package.json yarn.lock ./
RUN yarn install
COPY --chown=node:node . .
EXPOSE 3000
CMD ["yarn", "start:dev"]